---
# This playbook manually adds apt sources
# Invoke it with a list of space separated apt source names, or none to see the list of known names
# ex:
#  ansible-playbook add-apt-sources.yml
#  ansible-playbook add-apt-sources.yml --ask-become-pass -e "sources=docker"
#  ansible-playbook add-apt-sources.yml --ask-become-pass -e "sources='virtualbox docker jonathonf-vim-ppa'"
- name: Add apt sources
  hosts: localhost

  vars:
    sources: ''

  roles:
    - role: add-apt-sources
      vars:
        apt_sources: '{{ sources.split() }}'
