---
all:
  hosts:
    localhost:
      ansible_connection: local

  children:
    # Raspberry Pi 4+ instances
    # (currently all server and client pi's are 4+'s, so those groups are direct children)
    raspberrypi4:
      children:
        # Raspberry Pi wireguard VPN server.
        #   Multiple clients connect and have internet access
        pi_wg_server:
          hosts:
            pi-275.local:
            pi-275.275cpw:

        # Raspberry Pi wireguard VPN client
        #   Provides dhcp server for wired connection, routes all traffic from there
        #   through the wireguard VPN (to a wireguard server)
        pi_wg_client:
          hosts:
            pi-gilli.local:
            pi-robin.local:
            pi-eliza.local:

    # Hosts that live at 275 central park west  (IP addresses should be in /etc/hosts)
    cpw275:
      hosts:
        dean.275cpw:
        may.275cpw:
        lidiapoet.275cpw:
        pi-275.275cpw:

