---
- name: Setup newly install Kubuntu 22.04 for {{ username }}
  hosts: localhost

  vars_files:
    - ./vars/os-pkgs_vars.yml

  vars:
    username: mjl
    ppas:
      # latest python
      - ppa:deadsnakes/ppa

      # latest vim
      - ppa:jonathonf/vim

      # KeePassXC
      - ppa:phoerious/keepassxc

    flatpaks:
      # Signal
      - org.signal.Signal

      # Slack
      - com.slack.Slack

      # Chromium
      - org.chromium.Chromium

      # Postman - development UI tool for sending http requests
      - com.getpostman.Postman

      # MediaInfo
      - net.mediaarea.MediaInfo

    software_other_install_methods:
      debs:
        # latest node (not a ppa, will need to move elsewhere)
        - nodesource see https://github.com/nodesource/distributions#debinstall

        # BeyondCompare (not a ppa)
        - scootersoftware

        # TeamViewer (not a ppa)
        - teamviewer

        # latest VirtualBox (not a ppa)
        - virtualbox see https://websiteforstudents.com/how-to-install-virtualbox-on-ubuntu-20-04-18-04/

        # ripgrep
        - ripgrep see https://github.com/BurntSushi/ripgrep#installation

        # discord
        - discord see https://discord.com/ and download the deb

      other:
        # UKUU (Ubuntu Kernel Update Utility) (not a ppa)
        - teejeetech-uuku

        # Smartgit (https://syntevo.com)
        - bin/smartgit

    # Entries to add to hosts file
    lan_hosts: |
      192.168.111.50	marcie.local    marcie
      192.168.111.51	patty.local     patty
      192.168.111.52	sally.local     sally
      192.168.111.99	snoopy.local    snoopy
      192.168.111.98	thor.local      thor
      192.168.111.97	minecraft.local minecraft
      192.168.111.96	woodstock.local woodstock
      192.168.111.95	redbaron.local  redbaron
      192.168.111.94	pigpen.local    pigpen
      192.168.111.93	fenris.local    fenris


  tasks:
    - name: Update and Upgrade all current packages
      when: inventory_hostname != 'localhost'
      become: yes
      ansible.builtin.apt:
        update_cache: yes
        upgrade: full
      register: apt_upgrade

    - name: Reboot to ensure all upgrades take effect
      when:
        - inventory_hostname != 'localhost'
        - apt_upgrade.changed
      become: yes
      ansible.builtin.reboot:
        post_reboot_delay: 30

    - name: Add PPA repositories
      become: yes
      ansible.builtin.apt_repository:
        repo: '{{ item }}'
        update_cache: no
      loop: '{{ ppas }}'

    - name: Install standard packages
      become: yes
      ansible.builtin.apt:
        name: '{{ standard_pkgs }}'
        state: latest
        update_cache: yes

    - name: Add Flatpak remotes
      become: yes
      community.general.flatpak_remote:
        name: flathub
        method: system
        state: present
        flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

    - name: Install Flatpak applications
      become: yes
      community.general.flatpak:
        name: '{{ item }}'
        method: system
        state: present
      loop: '{{ flatpaks }}'

    - name: Add special group {{ item }}
      become: yes
      ansible.builtin.group:
        name: '{{ item }}'
        system: yes
        state: present
      loop:
        - sambashare
        - docker
        - vboxusers

    - name: Add {{ username }} user to groups
      become: yes
      ansible.builtin.user:
        name: '{{ username }}'
        groups:
          - adm
          - sudo
          - cdrom
          - dip
          - lpadmin
          - lxd
          - audio
          - video
          - plugdev
          - staff
          - games
          - users
          - sambashare
          - vboxusers
          - docker
        append: yes

    - name: Add .local tld to hosts file 127.0.1.1 entry
      become: yes
      ansible.builtin.lineinfile:
        path: /etc/hosts
        backrefs: yes
        regexp: '^127\.0\.1\.1\t(\S+)$'
        line: '127.0.1.1\t\1.local \1'

    - name: Add lan hosts to hosts file
      become: yes
      ansible.builtin.blockinfile:
        path: /etc/hosts
        insertafter: '^$'
        block: '{{ lan_hosts }}'

    - name: Disable side mouse buttons
      ansible.builtin.copy:
        src: ./files/Xmodmap
        dest: /home/{{ username }}/.Xmodmap
        force: no
        owner: '{{ username }}'
        group: '{{ username }}'
        mode: a=r,u+w,g+w

    - name: Disable automatic updates
      become: yes
      ansible.builtin.lineinfile:
        path: /etc/apt/apt.conf.d/20auto-upgrades
        search_string: '{{ item.find }}'
        line: '{{ item.line }}'
      loop:
        - find: 'APT::Periodic::Unattended-Upgrade'
          line: 'APT::Periodic::Unattended-Upgrade "0";'
        - find: 'APT::Periodic::Download-Upgradeable-Packages'
          line: 'APT::Periodic::Download-Upgradeable-Packages "0";'

    - name: Konsole config settings
      community.general.ini_file:
        path: /home/{{ username }}/.config/konsolerc
        no_extra_spaces: yes
        section: TabBar
        option: '{{ item.option }}'
        value: '{{ item.value }}'
      loop:
        - option: CloseTabButton
          value: None
        - option: TabBarVisibility
          value: AlwaysShowTabBar

    - name: Dolphin config settings
      community.general.ini_file:
        path: /home/{{ username }}/.config/dolphinrc
        no_extra_spaces: yes
        section: '{{ item[0] }}'
        option: '{{ item[1] }}'
        value: '{{ item[2] }}'
      loop:
        - [ DetailsMode, FontWeight, 50 ]
        - [ DetailsMode, PreviewSize, 22 ]
        - [ FoldersPanel, LimitFoldersPanelToHome, false ]
        - [ General, OpenExternallyCalledFolderInNewTab, false ]
        - [ General, SortingChoice, CaseSensitiveSorting ]
