---
- name: Setup newly install Kubuntu 22.04 for {{ username }}
  hosts: localhost

  vars_files:
    - ./vars/os-pkgs_vars.yml

  vars:
    username: mjl
    flatpaks:
      # Flatseal is a graphical utility to review and modify permissions from your Flatpak applications
      - com.github.tchx84.Flatseal

      # LocalSend - send files and messages over the local LAN network (ie to/from LocalSend on phone)
      - org.localsend.localsend_app

      # Signal
      - org.signal.Signal

      # Slack
      #- com.slack.Slack

      # Chromium
      - org.chromium.Chromium

      # Postman - development UI tool for sending http requests
      #- com.getpostman.Postman

      # MediaInfo is a convenient unified display of the most relevant technical and tag data for video and audio files
      - net.mediaarea.MediaInfo

      # Hamster is time tracking for individuals
      #- org.gnome.Hamster

    software_other_install_methods:
      debs:
        # BeyondCompare (not a ppa)
        - scootersoftware

        # TeamViewer (not a ppa)
        - teamviewer

        # latest VirtualBox (not a ppa)
        - virtualbox see https://websiteforstudents.com/how-to-install-virtualbox-on-ubuntu-20-04-18-04/

        # ripgrep
        - ripgrep see https://github.com/BurntSushi/ripgrep#installation

        # discord
        - discord see https://discord.com/ and download the deb

      other:
        # UKUU (Ubuntu Kernel Update Utility) (not a ppa)
        - teejeetech-uuku

        # Smartgit (https://syntevo.com)
        - bin/smartgit

        # Calibre (https://calibre-ebook.com) (cmd as of 2024-10-20)
        - 'sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sudo sh /dev/stdin'

    # Entries to add to hosts file
    lan_hosts: |
      192.168.111.50	marcie.54hardypond    marcie
      192.168.111.51	patty.54hardypond     patty
      192.168.111.52	sally.54hardypond     sally
      192.168.111.99	snoopy.54hardypond    snoopy
      192.168.111.98	thor.54hardypond      thor
      192.168.111.97	minecraft.54hardypond minecraft
      192.168.111.96	woodstock.54hardypond woodstock
      192.168.111.95	redbaron.54hardypond  redbaron
      192.168.111.94	pigpen.54hardypond    pigpen
      192.168.111.93	fenris.54hardypond    fenris
      192.168.1.61	dean.275cpw
      192.168.1.62	may.275cpw
      192.168.1.63	pi-275.275cpw
      192.168.1.71	lidiapoet.275cpw
      192.168.1.92	daisy.275cpw
      192.168.1.96	woodstock.275cpw


  roles:
    - role: add-apt-sources
      vars:
        apt_sources:
          # latest flatpak
          - flatpak-ppa
          # latest python
          - deadsnakes-ppa
          # KeePassXC
          - phoerious-keepassxc-ppa
          # official packaged firefox (not snap)
          - mozilla
          # nodejs from nodesource (see role for ver# installed)
          - nodesource
          # latest virtualbox VM
          - virtualbox
          # Docker
          - docker

  tasks:
    - name: Update and Upgrade all current packages
      when: inventory_hostname != 'localhost'
      become: yes
      ansible.builtin.apt:
        update_cache: yes
        upgrade: full
      register: apt_upgrade

    - name: Reboot to ensure all upgrades take effect
      when:
        - inventory_hostname != 'localhost'
        - apt_upgrade.changed
      become: yes
      ansible.builtin.reboot:
        post_reboot_delay: 30

    - name: Lower priority of Ubuntu apt repo package for firefox, so official mozilla repo or ppa takes precedence
      become: yes
      ansible.builtin.copy:
        dest: /etc/apt/preferences.d/firefox-no-snap.pref
        content: |
          Package: firefox*
          Pin: release o=Ubuntu*
          Pin-Priority: -1

          Package: firefox*
          Pin: release o=LP-PPA-mozillateam
          Pin-Priority: 100

    - name: Remove the firefox snap (other snaps may want to be removed manually)
      become: yes
      community.general.snap:
        name: firefox
        state: absent

    - name: Install standard packages
      become: yes
      ansible.builtin.apt:
        name: '{{ standard_pkgs }}'
        state: latest
        update_cache: yes

    - name: Add Flatpak remotes
      become: yes
      community.general.flatpak_remote:
        name: flathub
        method: system
        state: present
        flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

    - name: Install Flatpak applications
      become: yes
      community.general.flatpak:
        name: '{{ item }}'
        method: system
        state: present
      loop: '{{ flatpaks }}'

    - name: Add special group {{ item }}
      become: yes
      ansible.builtin.group:
        name: '{{ item }}'
        system: yes
        state: present
      loop:
        - sambashare
        - docker
        - vboxusers

    - name: Add {{ username }} user to groups
      become: yes
      ansible.builtin.user:
        name: '{{ username }}'
        groups:
          - adm
          - sudo
          - cdrom
          - dip
          - lpadmin
          - lxd
          - audio
          - video
          - plugdev
          - staff
          - games
          - users
          - sambashare
          - vboxusers
          - docker
        append: yes

    - name: Add .local tld to hosts file 127.0.1.1 entry
      become: yes
      ansible.builtin.lineinfile:
        path: /etc/hosts
        backrefs: yes
        regexp: '^127\.0\.1\.1\t(\S+)$'
        line: '127.0.1.1\t\1.local \1'

    - name: Add lan hosts to hosts file
      become: yes
      ansible.builtin.blockinfile:
        path: /etc/hosts
        insertafter: '^$'
        block: '{{ lan_hosts }}'

    - name: Disable side mouse buttons
      ansible.builtin.copy:
        src: ./files/Xmodmap
        dest: /home/{{ username }}/.Xmodmap
        force: no
        owner: '{{ username }}'
        group: '{{ username }}'
        mode: a=r,u+w,g+w

    - name: Use os-prober when building grub menu to find and add partions w/ other bootable OSs
      become: yes
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        search_string: GRUB_DISABLE_OS_PROBER=
        line: GRUB_DISABLE_OS_PROBER=false

    - name: Change grub menu to display distribution description (-d) instead of distributor ID (-i)
      become: yes
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        search_string: GRUB_DISTRIBUTOR=`lsb_release
        line: "GRUB_DISTRIBUTOR=`lsb_release -d -s 2> /dev/null || echo Debian`"

    - name: Change grub menu timeout style from hidden to menu
      become: yes
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        search_string: GRUB_TIMEOUT_STYLE=
        line: GRUB_TIMEOUT_STYLE=menu

    - name: Change grub menu default timeout from 0 to 10
      become: yes
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        search_string: GRUB_TIMEOUT=
        line: GRUB_TIMEOUT=10

    - name: Disable automatic updates
      become: yes
      ansible.builtin.lineinfile:
        path: /etc/apt/apt.conf.d/20auto-upgrades
        search_string: '{{ item.find }}'
        line: '{{ item.line }}'
      loop:
        - find: 'APT::Periodic::Unattended-Upgrade'
          line: 'APT::Periodic::Unattended-Upgrade "0";'
        - find: 'APT::Periodic::Download-Upgradeable-Packages'
          line: 'APT::Periodic::Download-Upgradeable-Packages "0";'

    - name: Konsole config settings
      community.general.ini_file:
        path: /home/{{ username }}/.config/konsolerc
        no_extra_spaces: yes
        section: TabBar
        option: '{{ item.option }}'
        value: '{{ item.value }}'
      loop:
        - option: CloseTabButton
          value: None
        - option: TabBarPosition
          value: Bottom
        - option: TabBarVisibility
          value: AlwaysShowTabBar

    - name: Dolphin config settings
      community.general.ini_file:
        path: /home/{{ username }}/.config/dolphinrc
        no_extra_spaces: yes
        section: '{{ item[0] }}'
        option: '{{ item[1] }}'
        value: '{{ item[2] }}'
      loop:
        - [ DetailsMode, FontWeight, 50 ]
        - [ DetailsMode, PreviewSize, 22 ]
        - [ FoldersPanel, LimitFoldersPanelToHome, false ]
        - [ General, OpenExternallyCalledFolderInNewTab, false ]
        - [ General, SortingChoice, CaseSensitiveSorting ]
